"""initial schema

Revision ID: f1ceb3f3319f
Revises: 
Create Date: 2026-09-30 18:54:44.570554
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f1ceb3f3319f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_email', 'login_attempts', ['email', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('ideas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('commercial_framing', sa.Text(), nullable=False),
    sa.Column('strength_signal', sa.Text(), nullable=True),
    sa.Column('raw_claims', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'candidate'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('candidate', 'selected', 'rejected')", name=op.f('ck_ideas_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ideas_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas'))
    )
    op.create_index('ix_ideas_user_id', 'ideas', ['user_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('month', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error')", name=op.f('ck_llm_calls_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_calls_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_user_month', 'llm_calls', ['user_id', 'month'], unique=False)
    op.create_table('ventures',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('idea_id', sa.BigInteger(), nullable=False),
    sa.Column('phase', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('cycle_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_cycles', sa.Integer(), server_default=sa.text('6'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('parent_venture_id', sa.BigInteger(), nullable=True),
    sa.Column('pivot_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'validated', 'killed', 'paused', 'pivoted')", name=op.f('ck_ventures_status')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_ventures_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_venture_id'], ['ventures.id'], name=op.f('fk_ventures_parent_venture_id_ventures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ventures_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventures'))
    )
    op.create_index('ix_ventures_idea_id', 'ventures', ['idea_id'], unique=False)
    op.create_index('ix_ventures_parent_venture_id', 'ventures', ['parent_venture_id'], unique=False)
    op.create_index('ix_ventures_user_id', 'ventures', ['user_id'], unique=False)
    op.create_table('bmc_elements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('venture_id', sa.BigInteger(), nullable=False),
    sa.Column('element_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'untested'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("element_name IN ('customer', 'problem', 'value_prop', 'channel', 'revenue')", name=op.f('ck_bmc_elements_element_name')),
    sa.CheckConstraint("status IN ('untested', 'mixed', 'confirmed', 'disconfirmed')", name=op.f('ck_bmc_elements_status')),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], name=op.f('fk_bmc_elements_venture_id_ventures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bmc_elements')),
    sa.UniqueConstraint('venture_id', 'element_name', name=op.f('uq_bmc_elements_venture_id_element_name'))
    )
    op.create_table('cycles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('venture_id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('todos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('persevere', 'pivot', 'kill')", name=op.f('ck_cycles_decision')),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], name=op.f('fk_cycles_venture_id_ventures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cycles'))
    )
    op.create_index('ix_cycles_venture_id_cycle_number', 'cycles', ['venture_id', 'cycle_number'], unique=False)
    op.create_table('launch_strategy',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('venture_id', sa.BigInteger(), nullable=False),
    sa.Column('funding_matches_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gtm_channels_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], name=op.f('fk_launch_strategy_venture_id_ventures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_launch_strategy'))
    )
    op.create_index('ix_launch_strategy_venture_id', 'launch_strategy', ['venture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_launch_strategy_venture_id', table_name='launch_strategy')
    op.drop_table('launch_strategy')
    op.drop_index('ix_cycles_venture_id_cycle_number', table_name='cycles')
    op.drop_table('cycles')
    op.drop_table('bmc_elements')
    op.drop_index('ix_ventures_user_id', table_name='ventures')
    op.drop_index('ix_ventures_parent_venture_id', table_name='ventures')
    op.drop_index('ix_ventures_idea_id', table_name='ventures')
    op.drop_table('ventures')
    op.drop_index('ix_llm_calls_user_month', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_ideas_user_id', table_name='ideas')
    op.drop_table('ideas')
    op.drop_table('users')
    op.drop_index('ix_login_attempts_email', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
